// File: zekenewsom-trade_journal/packages/electron-app/preload.js
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  backupDatabase: () => ipcRenderer.invoke('backup-database'),
  restoreDatabase: () => ipcRenderer.invoke('restore-database'),
  exportDataCSV: () => ipcRenderer.invoke('export-data-csv'),
  exportDataJSON: () => ipcRenderer.invoke('export-data-json'),
  exportDataXLSX: () => ipcRenderer.invoke('export-data-xlsx'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  testDbConnection: () => ipcRenderer.invoke('test-db'),
  logTransaction: (data) => ipcRenderer.invoke('log-transaction', data),
  logCSVTransaction: (data) => ipcRenderer.invoke('log-csv-transaction', data),
  getTrades: () => ipcRenderer.invoke('get-trades'),
  getTradeWithTransactions: (tradeId) => ipcRenderer.invoke('get-trade-with-transactions', tradeId),
  updateTradeDetails: (data) => ipcRenderer.invoke('update-trade-details', data),
  updateSingleTransaction: (data) => ipcRenderer.invoke('update-single-transaction', data),
  deleteSingleTransaction: (transactionId) => ipcRenderer.invoke('delete-single-transaction', transactionId),
  deleteFullTrade: (tradeId) => ipcRenderer.invoke('delete-full-trade', tradeId),
  getAnalyticsData: (filters) => ipcRenderer.invoke('get-analytics-data', filters),
  getEmotions: () => ipcRenderer.invoke('get-emotions'),
  getTradeEmotions: (tradeId) => ipcRenderer.invoke('get-trade-emotions', tradeId),
  saveTradeEmotions: (payload) => ipcRenderer.invoke('save-trade-emotions', payload),
  updateMarkPrice: (payload) => ipcRenderer.invoke('update-mark-price', payload),
  createAccount: (opts) => ipcRenderer.invoke('create-account', opts),
  renameAccount: (opts) => ipcRenderer.invoke('rename-account', opts),
  archiveAccount: (opts) => ipcRenderer.invoke('archive-account', opts),
  unarchiveAccount: (opts) => ipcRenderer.invoke('unarchive-account', opts),
  deleteAccount: (opts) => ipcRenderer.invoke('delete-account', opts),
  getAccounts: (opts = {}) => ipcRenderer.invoke('get-accounts', opts),
  getAccountById: (accountId) => ipcRenderer.invoke('get-account-by-id', accountId),
  addAccountTransaction: (opts) => ipcRenderer.invoke('add-account-transaction', opts),
  getAccountTransactions: (opts) => ipcRenderer.invoke('get-account-transactions', opts),
  getAccountBalance: (accountId) => ipcRenderer.invoke('get-account-balance', accountId),
  getAccountTimeSeries: (accountId) => ipcRenderer.invoke('get-account-time-series', accountId),
  getMaintenanceStatus: () => ipcRenderer.invoke('get-maintenance-status'),
  getAutocompleteData: (field) => ipcRenderer.invoke('get-autocomplete-data', field),
  // Add any new IPC calls here if you add new handlers in main.js
});