-- Migration: Add archived and deleted columns to accounts table if missing
-- ALTER TABLE accounts ADD COLUMN archived BOOLEAN NOT NULL DEFAULT 0;
-- ALTER TABLE accounts ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT 0;
